name: PyInstaller Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt install pip
        sudo apt install python3-tk
        pip install pyinstaller Pillow customtkinter packaging numpy CTkMenuBar
    - name: Build CLI with PyInstaller
      run: |
        python3 -m PyInstaller mc3ds-tm.spec
    - name: Build GUI with PyInstaller
      run: |
        python3 -m PyInstaller --onefile --hide-console hide-early --icon icon.ico --add-data assets:assets --add-data modules:modules --add-data icon.ico:. --add-data icon.png:. --hidden-import PIL --hidden-import PIL._imagingtk --hidden-import PIL._tkinter_finder mc3ds-tm-gui.py
    - uses: actions/upload-artifact@v3
      with:
        name: mc3ds-tm
        path: dist/
